title: "Headers"
description: |
  This page contains the headers used across all the website pages.
patterns:
  header-main:
    title: "Header"
    description: |
      This header appears at the top of every page.
