title: "Cards"
description: |
  Cards are used to describe important bits of information quickly on the website.
patterns:
  product-card:
    title: "Product Card"
    description: |
      This is the standard product card. It should always contain an image, title, product title and a price.
    width: 300
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  sale-card:
    title: "Sale Card"
    description: |
      This is a sale card and used when an item goes on sale. Must contain an image, title, product title, original price and a the current sale price.
    width: 300
  category-card:
    title: "Category Card"
    description: |
      A category card is used as link to different product sections on the website. The image should relate to the product itself.
    width: 300
