title: "Checkout"
description: |
  The page holds all the necessary pieces to build the checkout page website.
patterns:
  items:
    title: "Items"
    description: |
      The items holds all the items the user has chosen. It shows the title, chosen size, quantity, colour, price and subtotal. It should always be located at the top of the checkout page.
  cart-summary:
    title: "Cart Summary List"
    description: |
      The cart summary list contains the cost summary of all the items the user has chosen. The total price, shipping cost, taxes, and the total price. Located to the left of the checkout form, but at the bottom so it can be reviewed easily.
  checkout-form:
    title: "Checkout Form"
    description: |
      The checkout form contains all the necessary information for the user to fill out, submit, and pay for the products. It should be located left of the summary and below the items.
